pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name = 'base'),
    path('reserva/', ReservaListView.as_view(), name = 'reserva'),
    path('<slug:slug>/', ReservaDetailView.as_view(), name = 'dreserva'),

]

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/tutorialdjango/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('blog.urls', namespace = 'blog')),
    
]

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})
     

class Cliente(models.Model):
    cod_cliente = models.BigAutoField(primary_key=True, verbose_name="Código do Cliente")
    nome_cliente = models.CharField(max_length=200, verbose_name="Nome do Cliente")
    cpf_cliente = models.CharField(max_length=15, verbose_name="CPF do Cliente")
    telefone01_cliente = models.CharField(max_length=15, verbose_name="Telefone (01) do Cliente")
    telefone02_cliente = models.CharField(max_length=15, verbose_name="Telefone (02) do Cliente")
    email_cliente = models.EmailField(max_length=260, verbose_name="E-mail do Cliente")
    senha_cliente = models.CharField(max_length=20, verbose_name="Senha do Cliente")

    def __str__(self) -> str:
        return "{} ({})".format(self.cod_cliente, self.nome_cliente)


class Reserva(models.Model):
    cod_reserva = models.BigAutoField(primary_key=True, verbose_name="Código da Reserva")
    qtd_pessoas = models.IntegerField(verbose_name="Quantidade de Pessoas")
    data_reserva = models.DateField(verbose_name="Data da Reserva")
    horario_reserva = models.TimeField(verbose_name="Horário da Reserva")
    tempo_tolerancia = models.IntegerField(verbose_name="Tempo de Tolerância de Atraso")

    slug = models.SlugField(max_length=255, unique=True)
    
    cod_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)


    def __str__(self) -> str:
        return "Cód. R: {} ({})".format(self.cod_reserva, self.data_reserva)
        
    def get_absolute_url(self):
        return reverse("blog:dreserva", kwargs={"slug": self.slug})



class Mesa(models.Model):
    num_mesa = models.IntegerField(primary_key=True, verbose_name="Número da Mesa")
    capacidade_mesa = models.IntegerField(verbose_name="Capacidade de pessoas da Mesa")
    descricao_mesa = models.TextField(max_length=500, verbose_name="Descrição")

    def __str__(self) -> str:
        return "Mesa Nº{}".format(self.num_mesa)


class Possui(models.Model):
    qtd_mesas_reservadas = models.IntegerField(verbose_name="Quantidade de Mesas Reservadas")

    num_mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE)
    cod_reserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return "{} - Mesas reservadas: {}".format(self.cod_reserva, self.qtd_mesas_reservadas)


class Cardapio(models.Model):
    cod_produto = models.BigAutoField(primary_key=True, verbose_name="Código do Produto")
    nome_produto = models.CharField(max_length=45, verbose_name="Nome do Produto")
    descricao_produto = models.TextField(max_length=600, verbose_name="Descrição do Produto")
    preco_produto = models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Preço")
    porc_desconto = models.IntegerField(verbose_name="Porcentagem de Desconto do Produto")

    def __str__(self) -> str:
        return "Cód.: {} ({})".format(self.cod_produto, self.nome_produto)
    

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/views.py
from django.views.generic import DetailView, ListView

from .models import *


class PostListView(ListView):
    model = Post

class PostDetailView(DetailView):
    model = Post

class ReservaListView(ListView):
    model = Reserva

class ReservaDetailView(DetailView):
    model = Reserva

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <h2>
        {{ post.title }}
    </h2>
    <p class="date">
        Publicado em {{ post.created }} por {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="javascript:void(0);" onclick="history.back();">Voltar</a>
    </p>
{% endblock content %}

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}
    Meu blog
{% endblock title %}

{% block content %}
    {% for post in post_list  %}
        <article>
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="date">
                Publicado em: {{ post.created }} por {{ post.author }}
            </p>
            {{ post.body|linebreaks|truncatewords:10 }}
        </article>
    {% endfor %}
{% endblock content %}

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/templates/blog/reserva_detail.html
<!--
  Turno/Turma: 3º ANO - Informática - Matutino
  Grupo: PineApple
  Discentes:

    - Eduarda Negreiros Silva;
    - Filipe Silva Rodrigues de Almeida;
    - Karla Sophia Polgar Rocha;
    - Théo Tavernard da Rocha Machado;
    - Victor Lopes Rios.

-->



{% load static %}


<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>{{reserva.cod_reserva}} - Reserva</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/home.css' %}" rel="stylesheet">
        <link href="{% static 'css/nav-bar.css' %}" rel="stylesheet">
        <link href="{% static 'blog/base.html' %}" rel="stylesheet">
        <link href="{% static 'blog/reserva_list.html' %}" rel="stylesheet">


        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <!--jQuery-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        
        <script defer src="{% static 'js/script.js' %}"></script>
        
    
    </head>
    <body>

        <header>
            <nav class="nav">
                <a href="/" class="logo"><img src="{% static 'img/logo.png' %}"></a>
                <button class="hamburguer"></button>
                <ul class="nav-list">
                    <li class="nav_item"><a href="javascript:void(-1);" onclick="history.go(-2);">Home</a></li>
                    <li class="nav_item"><a href="javascript:void(0);" onclick="history.back();">Voltar</a></li>
                    
                </ul>
            </nav>
        </header>

        <main>


            <section id="reserva">

                <div class="testemunials">
                    <h3>Reserva</h3>
                    <h2>Mais Informações</h2>
                </div>

                <div id="table_RFeRNF">
                    <div class="r_funcionais">

                        <table>

                            <caption>Detalhes - Reserva {{reserva.cod_reserva}}</caption>

                            <thead>

                                <tr>
                                    <th scope="col">Código da Reserva</th>
                                    <th scope="col">Data</th>
                                    <th scope="col">Horário</th>
                                    <th scope="col">Quantidade de Pessoas</th>
                                    <th scope="col">Tempo de Tolerância de Atraso (min)</th>
                                    <th scope="col">Código do Cliente</th>


                                </tr>

                            </thead>

                            <tbody>

                                <tr>

                                    <td class="tdcod_center"> <a> {{ reserva.cod_reserva }}</a></td>
                                    <td class="tddes_justy"> <a> {{ reserva.data_reserva }}</a></td>
                                    <td class="tddes_justy"> <a> {{ reserva.horario_reserva }}</a></td>
                                    <td class="tddes_justy"> <a> {{ reserva.qtd_pessoas }}</a></td>
                                    <td class="tddes_justy"> <a> {{ reserva.tempo_tolerancia }}</a></td>
                                    <td class="tdcod_center"> <a> {{ reserva.cod_cliente }}</a></td>
                                    

                                </tr>


                            </tbody>

                        </table>

                    </div>


                </div>

                <div class="espacando"></div>
                <div class="espacando"></div>
            </section>

        </main>

        <footer>
            <div class="espacando"></div>
            <p>&copy; 2024 - PineApple Restaurante</p>
        
        </footer>
        
    
    </body>
</html>
</html>

pineapple_restaurante/pineapple_restaurante/projeto_integrador_pr/tutorialdjango/blog/templates/blog/reserva_list.html
<!--
  Turno/Turma: 3º ANO - Informática - Matutino
  Grupo: PineApple
  Discentes:

    - Eduarda Negreiros Silva;
    - Filipe Silva Rodrigues de Almeida;
    - Karla Sophia Polgar Rocha;
    - Théo Tavernard da Rocha Machado;
    - Victor Lopes Rios.

-->



{% load static %}


<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Reservas - PineApple Restaurante</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/home.css' %}" rel="stylesheet">
  <link href="{% static 'css/nav-bar.css' %}" rel="stylesheet">
  <link href="{% static 'base.html' %}" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!--jQuery-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  <script defer src="{% static 'js/script.js' %}"></script>
  
  
</head>
<body>
  <header>
    <nav class="nav">
      <a href="/" class="logo"><img src="{% static 'img/logo.png' %}"></a>
      <button class="hamburguer"></button>
      <ul class="nav-list">
        <li class="nav_item"><a href="javascript:void(0);" onclick="history.back();">Home</a></li>
        
      </ul>
    </nav>
  </header>

  <main>

    <section id="reserva">
        <div class="testemunials">
            <h3>Reservas</h3>
            <h2>Datas Ocupadas</h2>
        </div>
  
        <div id="table_RFeRNF">
          <div class="r_funcionais">
  
            <table>
  
              <!--<caption>Requisitos Funcionais (RF)</caption>-->
  
              <thead>
  
                <tr>
                  <th scope="col">Código da Reserva</th>
                  <th scope="col">Data</th>
                  <th scope="col">Mais Informações</th>
  
                </tr>
  
              </thead>
  
              <tbody>

                {% for reserva in object_list %}

                <tr>
                  <td class="tdcod_center"><a> {{ reserva.cod_reserva }}</a></td>
                  <td class="tddes_justy"><a> {{ reserva.data_reserva }}</a></td>

                  <td> <a href="{{ reserva.get_absolute_url }}" class="leia" title="Ver mais">Ver mais</a></td>

  
                </tr>

                
                {% empty %}

                <tr class="tdcod_center">
                  <td colspan="3">Nenhuma Reserva registrada.</td>
  
                </tr>

                {% endfor %}

        

              </tbody>
  
            </table>
  
          </div>
  
  
        </div>
        <div class="espacando"></div>
        <div class="espacando"></div>
    </section>


  </main>

  <footer>
    <div class="espacando"></div>
    <div>
      <ul class="horario">
        <li><p>Abrimos de</p></li>
        <li><p>Segunda a Domingo</p></li>
        <li><p>--- 11:00 - 15:00 ---</p></li>
        <li><p>--- 18:00 - 23:00 ---</p></li>
      </ul>
    </div>
    <p>&copy; 2024 - PineApple Restaurante</p>
  </footer> 


</body>
</html>
</html>